### PR TITLE
updates to get code in line with changes in pipeline/bin

### PR DESCRIPTION
**Pull request by teharrison**

### CODE REVIEW

**Comment by teharrison** [comment]
not sure if kevin can merge pull request, but he should take a peek at this.

**Comment by DrOppenheimer** [comment]
Were all of these changes run on a set of samples to see how they affect the DRISEE outputs -- this has to be done before the changes are implemented

**Comment by teharrison** [comment]
I guess i wasn't explicit enough.  These are all changes that were already done / already exist in the pipeline scripts, and are currently running on the pipeline.

**Comment by DrOppenheimer** [comment]
Got it now -- thanks
I merged the pull

Cheers
K

On Wed, Aug 1, 2012 at 2:19 PM, teharrison <
reply@reply.github.com

> wrote:
> 
> I guess i wasn't explicit enough.  These are all changes that were already
> done / already exist in the pipeline scripts, and are currently running on
> the pipeline.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MG-RAST/DRISEE/pull/1#issuecomment-7437100

## 

Kevin

---

Kevin P. Keegan, PhD

Argonne National Laboratory (work)
9700 South Cass Avenue
Bldg. 240, Rm. 4.G.14
Argonne, IL 60439
(630)252-3703
kkeegan@anl.gov

kevin.p.keegan@gmail.com (home)
(847)733-1079

**Pull request merged**
